### ISSUE TITLE
Excess Script Contents

### ISSUE THREAD

**Issue by EvanHsieh0415** [MDReal32/bundled-kubejs#1]
[bundled-kubejs / kubejs / client_scripts / script.js](https://github.com/MDReal32/bundled-kubejs/blob/master/kubejs/client_scripts/script.js)
![圖片](https://github.com/MDReal32/bundled-kubejs/assets/74277414/fe2faab5-af2f-46bd-9e8f-b8b63f82f372)

**Comment by MDReal32** [comment]
That's one is example script and core of that scrtipt inside `src/client.ts`
